maintainer       "Matt Halliday"
maintainer_email "matthalliday@gmail.com"
license          "MIT"
description      "Configuration for web apps using PHP"
long_description "See README.md for more detailed information"
version          "0.2.0"
supports         "ubuntu"
depends          "apache2"
